### PR TITLE
Setting DGI as maintainer.

### PR DESCRIPTION
**Pull request by willtp87**
@dannylamb 

I'm unsure of the correct procedure around this but discoverygarden would like to become the maintainer on this repo.

### CODE REVIEW

**Comment by dannylamb** [comment]
@willtp87 We didn't specify, but README PRs are definitely the right procedure for this.

I'm fine with leaving the discoverygarden email address because I'm sure that the work will be supported by the entire organization, but can we get an individual's name on there as well so that someone can get tagged?

**Comment by willtp87** [comment]
@dannylamb How's that look?

**Review by dannylamb — APPROVED** [review]
:+1: :shipit:

**Comment by dannylamb** [comment]
@willtp87 Just wating on travis as a formality.  Thanks man.

**Comment by willtp87** [comment]
@dannylamb  Thanks!

**Pull request merged**
